backend:
  name: git-gateway
  branch: master
site_url: https://hipup.org

media_folder: static/img
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/_pages/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Mission", name: "mission", widget: "text" }
        - { label: "Group Photo", name: "group_photo", widget: "text" }
    - label: "Contact"
      name: "contact"
      file: "content/_pages/contact.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
  - label: "All Projects"
    label_singular: "Project"
    name: "projects"
    folder: "content/_projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Current", name: "is_current", widget: "boolean" }
      - { label: "Project Logo", name: "logo", widget: "image" }
      - { label: "Project Image", name: "cover image", widget: "image" }
      - label: "Eligibilty"
        label_singular: "requirement"
        name: "requirements"
        widget: "list"
        fields:
          - { label: "Requirement", name: "requirement", widget: "text" }
      - label: "Team Members"
        name: "team_members"
        label_singular: "member"
        widget: "list"
        fields:
          - label: "Member"
            name: "title"
            widget: "relation"
            collection: "team"
            displayFields: ["title", "project"] 
            searchFields: ["title", "project"]
            valueField:  "title"
  - label: "Publications"
    label_singular: "Category"
    name: "publications"
    folder: "content/_publications"
    create: true
    fields:
      - { label: "Category", name: "title", widget: string }
      - label: "Publications"
        name: "publications"
        widget: list
        fields:
          - { label: "Title", name: "title", widget: string }
          - { label: "Date Published", name: "date_published", widget: date }
          - { label: "Description", name: "publication_description", widget: text }
          - { label: "File Upload", name: "publication_file", widget: file }
  - label: "Team Members"
    label_singular: " Team Member"
    name: "team"
    folder: "content/_team"
    widget: "object"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image", default: "/static/img/avatar.png" }
      - { label: "Bio", name: "bio", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - label: "Project(s)"
        name: "projects"
        widget: "relation"
        collection: "projects"
        multiple: true
        displayFields: ["title", "project"] 
        searchFields: ["title", "project"]
        valueField:  "title"
      - { label: "Public", name: "public", widget: "boolean", default: true }
  